title: Siddharth Jeetendra Choudhari
logo: /assets/logo.png
description: INSTRUMENTATION ENGINEER | 7 YEARS WORK - EX IN CORE INSTRUMENTATION FIELD | PURSUIING EPG + MS IN AI ML FROM IIIT-B AND LJMU
show_downloads: false
theme: jekyll-theme-minimal
